### ISSUE TITLE
WebChat

### ISSUE THREAD

**Issue by radike** [vaclavHala/SpatialTracker#17]
Each issue has a chat. The chat is realtime and uses WebSocket (no refresh on a new message).

**Comment by radike** [comment]
WebChat is implemented. Only thing to do is proper configuration of Infinispan, which will be used as persistent storage of WebChat's messages. I will use the configuration that will be implemented by @OndrejPontes

**Comment by OndrejPontes** [comment]
CRUD will be enough ?

**Comment by radike** [comment]
Only Create and Retrieve. See [WebChatMessageStore](https://github.com/vaclavHala/SpatialTracker/blob/master/src/main/java/cz/muni/fi/pv243/spatialtracker/webchat/store/WebChatMessageStore.java)

**Comment by OndrejPontes** [comment]
Is there any ID or something unique for each message ?

**Comment by radike** [comment]
If it is necessary then feel free to add ID or something else, but as long as we want to only store and retrieve messages, the messages can be without unique identificator.

**Comment by OndrejPontes** [comment]
a ako chces ziskat spravy spat a v spravnom poradi ak nemas nejake idcka ?

**Comment by radike** [comment]
See [WebChatMessageStore](https://github.com/vaclavHala/SpatialTracker/blob/master/src/main/java/cz/muni/fi/pv243/spatialtracker/webchat/store/WebChatMessageStore.java). The order of the messages is given by their order in the List.

**Comment by vaclavHala** [comment]
Fixed the AQ test setup for web chat, see branch web-tests. This setup should be usable in all other Infinispan tests as well. 

There were two errors:
- Creating a JavaArchive instead of WebArchive. Also beans.xml was added to manifest folder instead of web-inf.
- Adding Infinispan manually instead of resolving it via Maven. Transitive deps were missing (this is impossible to ever do right by hand really...)
