### ISSUE TITLE
JMS 2.0 API

### ISSUE THREAD

**Issue by radike** [vaclavHala/SpatialTracker#18]
JMS 2.0 API is used to integrate with some another systems, e.g. with some work management system.

**Comment by radike** [comment]
What are we going to send to the JMS?

**Comment by vaclavHala** [comment]
I'd emit a JMS message every time issue is claimed/resolved by a worker.  It would look like this:

Im a worker, I come to work in the morning and need something to work on today. I check reported issues in my work area and pick a few I'll handle today. I claim the issues, their state changes to ACCEPTED and JMS message is sent out. My manager has software which consumes these messages from all our systems (our issue tracker is one of these) and he can easily see what everyone is doing.

The 'aggregation from many systems' part makes the JMS messages at least a bit useful. Messages can be collected and viewed in one place instead of having to browse many issue trackers, calendars etc.
